### ISSUE TITLE
Launch in pip

### ISSUE THREAD

**Issue by bruAristimunha** [gemeinl/braindecode-features#2]
Hi :)

I love your work! 

Do you have the prospect of integrating this module in braindecode or launching it individually in pip?

**Comment by gemeinl** [comment]
Hi @bruAristimunha !
Thanks a lot! 
Yes, the plan is to definitely integrate the library into braindecode / launch the library on pip at some point. Currently, I cannot give a time frame for this though. Code is still under heavy construction and important features are still missing...
